server:
  port: ${SERVER_PORT:5000}
  address: ${SERVER_ADDRESS:0.0.0.0}

spring:
  application:
    name: Api-Gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: User-Service
            uri: ${USER_SERVICE_URL:http://localhost:5001}
            predicates:
              - Path=/user/**
            filters:
              - StripPrefix=0

          - id: Memory-Service
            uri: ${MEMORY_SERVICE_URL:http://localhost:5002}
            predicates:
              - Path=/memory/**
            filters:
              - StripPrefix=0
